m = 11.0
Jx = 0.824
Jy = 1.135
Jz = 1.759
Jxz = 0.120
S = 0.55
b = 2.9
c = 0.19
rho = 1.268
e = 0.9
Vmax = 44.4
Dprop = 0.508
KV = 0.0659
KQ = 0.0659
Rmotor = 0.042
i0 = 1.5
CQ2 = -0.1079
CQ1 = -0.06044
CQ0 = 0.09357
CT2 = -0.1079
CT1 = -0.06044
CT0 = 0.09357
CL0 = 0.23
CD0 = 0.043
Cm0 = 0.0135
CL_alpha = 5.61
CD_alpha = 0.030
Cm_alpha = -2.74
CL_q = 7.95
CD_q = 0.0
Cm_q = -38.21
CL_delta_e = 0.13
CD_delta_e = 0.0135
Cm_delta_e = -0.99
M = 50.0
alpha0 = 0.47
CD_p = 0.043
CY_beta = -0.83
Cl_beta = 0.0
Cn_beta = 0.073
CY_p = 0.0
Cl_p = -0.51
Cn_p = -0.069
CY_r = 0.0
Cl_r = 0.25
Cn_r = -0.095
CY_delta_a = 0.075
Cl_delta_a = 0.17
Cn_delta_a = -0.011
Cl_delta_r = 0.0024
Cn_delta_r = -0.069
